import os
import shutil
import asyncio
import tempfile
import json
import sys
from pathlib import Path
from typing import List, Optional
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

# Add CORS middleware to allow cross-origin requests (including WebSocket)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify your frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Data Models ---
class TestFile(BaseModel):
    filename: str
    content: str

class TestRequest(BaseModel):
    repo_url: str
    branch: str = "main"
    test_files: List[TestFile] = [] # New tests generated by AI to inject
    install_command: Optional[str] = None
    test_command: Optional[str] = None

# --- Helper: Async Subprocess Runner ---
async def run_command(cmd: str, cwd: str, websocket: WebSocket):
    """
    Runs a shell command and streams output to the websocket.
    """
    await websocket.send_json({"type": "log", "data": f"> {cmd}"})
    
    process = await asyncio.create_subprocess_shell(
        cmd,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE
    )

    async def stream_output(stream, stream_type):
        while True:
            line = await stream.readline()
            if not line:
                break
            decoded = line.decode('utf-8', errors='replace').strip()
            if decoded:
                # Send log to frontend
                await websocket.send_json({
                    "type": "output", 
                    "stream": stream_type, 
                    "data": decoded
                })

    # Read stdout and stderr concurrently
    await asyncio.gather(
        stream_output(process.stdout, "stdout"),
        stream_output(process.stderr, "stderr")
    )

    return_code = await process.wait()
    
    if return_code != 0:
        await websocket.send_json({"type": "error", "data": f"Command failed with exit code {return_code}"})
        raise Exception(f"Command failed: {cmd}")
    
    await websocket.send_json({"type": "success", "data": f"Command finished successfully."})

# --- WebSocket Endpoint ---
@app.websocket("/ws/run-tests")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    temp_dir = None

    try:
        # 1. Wait for configuration payload
        data = await websocket.receive_text()
        payload = json.loads(data)
        request = TestRequest(**payload)

        # 2. Create Temporary Directory
        temp_dir = tempfile.mkdtemp(prefix="medtest_runner_")
        await websocket.send_json({"type": "status", "step": "setup", "message": f"Created temp environment: {temp_dir}"})

        # 3. Clone Repository
        await websocket.send_json({"type": "status", "step": "cloning", "message": f"Cloning {request.repo_url}..."})
        # Note: In production, sanitize repo_url to prevent command injection
        await run_command(f"git clone --depth 1 {request.repo_url} .", temp_dir, websocket)

        # 4. Inject Generated Test Files
        if request.test_files:
            await websocket.send_json({"type": "status", "step": "injecting", "message": "Injecting AI-generated test files..."})
            for test_file in request.test_files:
                file_path = Path(temp_dir) / test_file.filename
                # Ensure parent dirs exist (e.g., if filename is 'tests/test_gen.py')
                file_path.parent.mkdir(parents=True, exist_ok=True)
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(test_file.content)
                await websocket.send_json({"type": "log", "data": f"Wrote file: {test_file.filename}"})

        # 5. Detect Environment & Install Dependencies
        # We will use a virtual environment to avoid polluting the server
        venv_path = os.path.join(temp_dir, "venv")
        
        # Windows vs Unix paths for venv python
        if sys.platform == "win32":
            venv_python = os.path.join(venv_path, "Scripts", "python.exe")
            venv_pip = os.path.join(venv_path, "Scripts", "pip.exe")
        else:
            venv_python = os.path.join(venv_path, "bin", "python")
            venv_pip = os.path.join(venv_path, "bin", "pip")

        await websocket.send_json({"type": "status", "step": "installing", "message": "Creating virtual environment..."})
        await run_command(f"{sys.executable} -m venv {venv_path}", temp_dir, websocket)

        # Install Deps
        await websocket.send_json({"type": "status", "step": "installing", "message": "Installing dependencies..."})
        
        if (Path(temp_dir) / "requirements.txt").exists():
             await run_command(f"{venv_pip} install -r requirements.txt", temp_dir, websocket)
             # Install pytest if not present, as we need a runner
             await run_command(f"{venv_pip} install pytest", temp_dir, websocket)
        elif (Path(temp_dir) / "package.json").exists():
            # Node.js handling (optional, based on your preference)
            await websocket.send_json({"type": "log", "data": "Node.js project detected. Using npm."})
            await run_command("npm install", temp_dir, websocket)
        else:
            await websocket.send_json({"type": "warning", "data": "No requirements.txt found. Trying to run tests anyway."})

        # 6. Run Tests
        await websocket.send_json({"type": "status", "step": "running", "message": "Executing test suite..."})
        
        test_cmd = request.test_command
        if not test_cmd:
            if (Path(temp_dir) / "package.json").exists():
                test_cmd = "npm test"
            else:
                # Default Python Command: run pytest on the whole folder
                test_cmd = f"{venv_python} -m pytest"

        await run_command(test_cmd, temp_dir, websocket)

        # 7. Final Success
        await websocket.send_json({"type": "complete", "status": "passed", "message": "All steps completed."})

    except WebSocketDisconnect:
        print("Client disconnected")
    except Exception as e:
        await websocket.send_json({"type": "complete", "status": "failed", "message": str(e)})
    finally:
        # 8. Cleanup
        if temp_dir and os.path.exists(temp_dir):
            try:
                shutil.rmtree(temp_dir)
                print(f"Cleaned up {temp_dir}")
            except Exception as e:
                print(f"Failed to cleanup {temp_dir}: {e}")
        await websocket.close()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)